nelmio_api_doc:
    documentation:
        servers:
          - url: localhost
            description: Api is over 
        info:
            title: La guilde des seigneurs
            description: This is an awesome app!
            version: "0.11"
    areas: # to filter documented areas
        path_patterns:
            - ^/((?!api|_error).*$) # Accepts routes under /api except /api/doc
